---
jobs:
  build:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Add elm-review, elm and elm-format to path
        run: yarn bin >> $GITHUB_PATH
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: sparksp/elm-review-action@v1
      - name: Run unit tests
        run: yarn run test
      - name: Make index.html
        run: yarn run build
      - uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages
          path: public/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
name: CI
'on':
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: null